[package]
name = "emma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.5"
slab = "0.4"
woke = "0.0.2"

[dev-dependencies]
tokio = { version = "1.17.0", features = ["rt"] }
